# Dependabot configuration file
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Frontend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    # Group all npm updates into a single PR
    groups:
      npm-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    # Ignore specific dependencies if needed
    # ignore:
    #   - dependency-name: "example-dependency"
    #     versions: ["1.x", "2.x"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"